- name: Register variables
  hosts: all
  tasks:
    - name: ls command
      ansible.builtin.shell: ls
      register: out

    - name: Print output
      ansible.builtin.debug:
        msg: "{{out.stdout}}"

    - name: Declare a variable
        ansible.builtin.set_fact:
          CMD_OUTPUT: "{{out.stdout}}"

